#!/usr/bin/env ruby
require 'fileutils'

cmd = ARGV.first
address = cmd
address = ARGV[1] if ARGV.length == 2

  if address !~ /https:\/\/github\.com/
    address = "https://github.com/#{address}.git" 
  end
  repo = address.split('/').last
  repo.slice! ".git"

case cmd
when "list"
  puts Dir.glob(File.join(ENV['HOME'], ".vim", "bundle", "*")).map{|s| s.split('/').last}
when "user"
  `rm -rf ~/.vim ~/.vimrc ~/.gvimrc`
  `git clone #{address} ~/.vim`
  Dir.chdir(File.join(ENV["HOME"], ".vim"))
  `git submodule init`
  `git submodule update`
  `ln -s ~/.vim/.vimrc ~/.vimrc`
  `ln -s ~/.vim/.gvimrc ~/.gvimrc`
when "down"
  Dir.chdir(File.join(ENV["HOME"], ".vim", "bundle"))
  FileUtils.rm_rf repo
else
  Dir.chdir(File.join(ENV["HOME"], ".vim", "bundle"))
  FileUtils.rm_rf repo
  `git clone #{address}`
end
